---
layout: homepage
---

## About Me

I am an undergraduate student majoring in Mathematics and Computer Science at New York University, and an incoming Master of Science student in Data Science at Harvard University (September 2025). My research interests focus on artificial intelligence, computer vision, and medical image analysis. Currently, I work as a research assistant at the AI4CE Lab at NYU Tandon and the Radiology Research Department at NYU Langone Health, where I contribute to projects in 3D reconstruction, assembly, and medical imaging analysis.

## Education

- **Harvard University** | Master of Science in Data Science (Incoming) | Sept 2025 - Dec 2026
- **New York University** | Bachelor of Art in Mathematics and Computer Science (GPA: 3.883/4.000) | Sept 2022 - May 2025

## Research Experience

### NYU Tandon, AI4CE Lab (supervised by Prof. Chen Feng)
*Research Assistant | Aug 2024 - Present*
- **3D Assembly Project**: Second author on "GARF: Learning Generalizable 3D Reassembly for Real-World Fractures," submitted to ICCV 2025
- Processed archaeopteryx thoracic and spinal bone fragments for assembly using PuzzleFusion and Jigsaw models, improving fragment analysis accuracy by 25%
- Implemented the BreakingGood process and handled simulations of trained data, resulting in a 50% increase in trained data variety
- **3D Reconstruction Project**: Implemented Dust3R geometric 3D vision model for archaeological fragment reconstruction, optimizing scanning methods to enhance model accuracy

### NYU Langone Health, Radiology Research Department (supervised by Dr. Yiqiu Shen)
*Research Assistant | Feb 2024 - Present*
- **Pancreatic Cancer Project**: Performed data cleansing and processing for 1200+ pancreatic cancer patients, using Large Language Models to process radiology reports
- **Breast Cancer Project**: Conducted statistical analysis on 200 radiology report pairs using Cohen's Kappa hypothesis test to verify consistency between GPT-generated and radiologist-assigned BI-RADS scores
- Enhanced GPT training prompt template for BI-RADS score ratings, achieving a 10% increase in scoring consistency through literature review on Prompt Engineering

### Chongqing University of Technology (supervised by Prof. Dongyang Qiu)
*Research Assistant | Nov 2023 - Present*
- Implemented machine learning algorithms including Support Vector Machine (SVM) and ensemble classifiers to build early warning models for systemic financial risk
- Developed data preprocessing tools, particularly web scraping tools, reducing processing time by 15%

### NYU Savin's Lab (supervised by Prof. Cristina Savin)
*Research Assistant | Nov 2023 - May 2024*
- Participated in dimensionality reduction and feature extraction of high-dimensional data using PCA and factor analysis
- Conducted research on Gaussian Models for optimizing data modeling, prediction, and clustering

## Professional Experience

### Guotai Jun'an Securities
*Investment Banking Intern | May 2023 - July 2023*
- Spearheaded project proposals for client companies, focusing on market research, comparable company analysis, and accounting assessments
- Contributed to 10+ high-profile roadshows for client company offerings, documenting insights and consolidating key takeaways (project resulted in successful IPO)
- Produced financial offering-related documents, including accounting due diligence and client interviews

## Teaching & Volunteering

### Courant Institute of Mathematical Sciences
*Teaching Assistant | Feb 2024 - Present*
- Served as TA for Linear Algebra and Calculus III for 5 academic terms, providing one-on-one tutoring and grading assignments for 50+ students

### NYU Project Sunshine
*Member | Sept 2022 - March 2024*
- Assembled craft kits and coordinated deliveries to hospitalized children to improve quality of life for pediatric patients

## Skills

- **Technical Proficiency**: R, Java, Python, C, SPSS Statistics, SQL, CSS, HTML, GIS
- **Languages**: Mandarin Chinese (Native), English (Fluent)
